name: Update data.json

# 이벤트 설정: 매일 자정에 자동으로 실행되도록 설정하거나, 수동으로 실행할 수 있도록 설정
on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:  # 수동으로 실행 가능

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Fetch data from Web App
      run: |
        curl -o data.json "https://script.google.com/macros/s/AKfycbyoKMoftj3_1qvycSXb2KjuMkqj62q4gttGlPy8mjCYKo43Jn3oTM2k093LQss0sAqv/exec"

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data.json
        git commit -m "Automated update data.json"
        git push
